import { useState, useEffect } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import {
  Box,
  Button,
  Container,
  Header,
  SpaceBetween,
  Alert,
  Tabs,
  Spinner,
  ColumnLayout,
  KeyValuePairs,
  Badge,
  StatusIndicator,
  Icon,
  ExpandableSection,
  ProgressBar,
} from '@cloudscape-design/components';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import { readInventory, invokeAnalyze, invokeTransform } from '../agentcore';
import { getStatusConfig, getAlertConfig, PRIORITY_COLORS } from '../constants';

function GenAiLabel() {
  return (
    <Box variant="awsui-gen-ai-label" fontSize="body-s">
      <Icon name="gen-ai" size="small" />
      Generated by AI
    </Box>
  );
}

interface FunctionRecord { function_arn: string; [key: string]: unknown; }

function extractFunctionName(arn: string): string {
  return arn.match(/function:(.+)/)?.[1] || arn;
}
function formatDate(d?: string): string {
  if (!d) return '—';
  try { return new Date(d).toLocaleDateString(undefined, { year: 'numeric', month: 'short', day: 'numeric', hour: '2-digit', minute: '2-digit' }); }
  catch { return d; }
}
function formatBytes(b?: number): string {
  if (!b) return '—';
  if (b < 1024) return `${b} B`;
  if (b < 1048576) return `${(b / 1024).toFixed(1)} KB`;
  return `${(b / 1048576).toFixed(1)} MB`;
}
function formatElapsed(s: number): string {
  const m = Math.floor(s / 60);
  const sec = s % 60;
  return m > 0 ? `${m}m ${sec}s` : `${sec}s`;
}

export default function FunctionDetail() {
  const { arn } = useParams<{ arn: string }>();
  const navigate = useNavigate();
  const decodedArn = arn ? decodeURIComponent(arn) : '';
  const functionName = extractFunctionName(decodedArn);

  const [item, setItem] = useState<FunctionRecord | null>(null);
  const [loading, setLoading] = useState(true);
  const [actionLoading, setActionLoading] = useState<string | null>(null);
  const [actionError, setActionError] = useState<string | null>(null);
  const [analyzeResult, setAnalyzeResult] = useState<Record<string, unknown> | null>(null);
  const [transformResult, setTransformResult] = useState<Record<string, unknown> | null>(null);
  const [activeTab, setActiveTab] = useState('overview');
  const [transformProgress, setTransformProgress] = useState<
    { done?: number; total?: number; phase?: string; attempt?: number } | null
  >(null);
  const [elapsed, setElapsed] = useState(0);

  // Elapsed-time counter while a transform is running
  useEffect(() => {
    if (actionLoading !== 'transform') { setElapsed(0); return; }
    const start = Date.now();
    const id = setInterval(() => setElapsed(Math.floor((Date.now() - start) / 1000)), 1000);
    return () => clearInterval(id);
  }, [actionLoading]);

  // Poll inventory for the transform progress heartbeat while a transform runs.
  // The blocking invoke still delivers the final result; this only feeds the
  // live "X/N" counter from the agent's DynamoDB progress writes.
  useEffect(() => {
    if (actionLoading !== 'transform') { setTransformProgress(null); return; }
    let cancelled = false;
    let timer: ReturnType<typeof setTimeout>;
    async function poll() {
      try {
        let result = await readInventory();
        if (typeof result === 'string') try { result = JSON.parse(result); } catch { /* */ }
        const typed = result as { functions: FunctionRecord[] } | null;
        const fn = typed?.functions?.find(f => f.function_arn === decodedArn) as any;
        if (!cancelled && fn?.transform_progress) setTransformProgress(fn.transform_progress);
      } catch { /* ignore poll errors — display falls back to elapsed time */ }
      if (!cancelled) timer = setTimeout(poll, 5000);
    }
    timer = setTimeout(poll, 4000);
    return () => { cancelled = true; clearTimeout(timer); };
  }, [actionLoading, decodedArn]);

  // Load function data from inventory
  useEffect(() => {
    async function load() {
      try {
        let result = await readInventory();
        if (typeof result === 'string') try { result = JSON.parse(result); } catch { /* */ }
        const typed = result as { functions: FunctionRecord[] } | null;
        const fn = typed?.functions?.find(f => f.function_arn === decodedArn);
        if (fn) {
          setItem(fn);
          // Pre-populate assessment
          if ((fn as any).migration_complexity || (fn as any).assessed_at) {
            setAnalyzeResult({
              complexity: (fn as any).migration_complexity, target_runtime: (fn as any).target_runtime,
              summary: (fn as any).assessment_summary, migration_risks: (fn as any).migration_risks,
              deprecated_apis: (fn as any).deprecated_apis, breaking_changes: (fn as any).breaking_changes,
              dependency_issues: (fn as any).dependency_issues, lines_of_code: (fn as any).lines_of_code,
              num_source_files: (fn as any).num_source_files, current_runtime: (fn as any).runtime,
              assessed_at: (fn as any).assessed_at, s3_original_code_path: (fn as any).s3_original_code_path,
              s3_findings_path: (fn as any).s3_findings_path,
            });
          }
          // Pre-populate transform
          if ((fn as any).transformed_at) {
            const rt = ((fn as any).runtime || '').toLowerCase();
            setTransformResult({
              migration_status: (fn as any).migration_status, s3_path: (fn as any).s3_migrated_code_path || '',
              transformed_at: (fn as any).transformed_at || '', changelog: (fn as any).changelog || '',
              validation: (fn as any).validation_result
                || ((fn as any).transform_error ? { valid: false, errors: [(fn as any).transform_error] } : { valid: true, errors: [] }),
              migrated_files: (fn as any).migrated_files_list || [],
              status: (fn as any).migration_status === 'READY_TO_MIGRATE' ? 'complete' : 'validation_failed',
            });
          }
        }
      } catch { /* */ }
      finally { setLoading(false); }
    }
    load();
  }, [decodedArn]);

  async function handleAnalyze() {
    setActionLoading('analyze'); setActionError(null); setActiveTab('assessment');
    try {
      let r = await invokeAnalyze(decodedArn);
      if (typeof r === 'string') try { r = JSON.parse(r); } catch { /* */ }
      setAnalyzeResult(r as Record<string, unknown>);
    } catch (e) { setActionError(e instanceof Error ? e.message : 'Analysis failed'); }
    finally { setActionLoading(null); }
  }

  async function handleTransform() {
    setActionLoading('transform'); setActionError(null); setActiveTab('transform');
    try {
      let r = await invokeTransform(decodedArn);
      if (typeof r === 'string') try { r = JSON.parse(r); } catch { /* */ }
      setTransformResult(r as Record<string, unknown>);
    } catch (e) { setActionError(e instanceof Error ? e.message : 'Transform failed'); }
    finally { setActionLoading(null); }
  }

  if (loading) return <Box textAlign="center" padding="xxxl"><Spinner size="large" /><Box variant="p" padding={{ top: 's' }}>Loading...</Box></Box>;
  if (!item) return <Alert type="error">Function not found: {decodedArn}</Alert>;

  const i = item as any;
  const tags = i.tags || {};
  const layers = i.layers || [];
  const envVars = i.env_vars || {};


  // ─── Overview Tab ───
  const overviewTab = (
    <SpaceBetween size="l">
      <Box variant="p" color="text-body-secondary">Discovers Lambda functions running deprecated runtimes via Trusted Advisor, enriches each with Lambda API configuration and CloudWatch invocation metrics, then uses Nova 2 Lite to calculate a migration priority score.</Box>
      <Container>
    <ColumnLayout columns={4} variant="text-grid">
      <SpaceBetween size="s">
        <Header variant="h3" description='We use the "AWS Lambda Functions Using Deprecated Runtimes" (L4dfs2Q4C5) AWS Support API Security Check to fetch the below data'>Source: AWS Trusted Advisor</Header>
        <KeyValuePairs columns={1} items={[
          { label: 'Function ARN', value: <Box variant="code" fontSize="body-s">{i.function_arn}</Box> },
          { label: 'Region', value: i.region || '—' },
          { label: 'Runtime', value: i.runtime || '—' },
          { label: 'Alert Status', value: (() => { const c = getAlertConfig(i.alert_status || ''); return <Badge color={c.color as any}>{c.label}</Badge>; })() },
          { label: 'Deprecation Date', value: i.deprecation_date || '—' },
          { label: 'Days to Deprecation', value: i.days_to_deprecation != null ? String(i.days_to_deprecation) : '—' },
          { label: 'Avg Daily Invokes', value: i.avg_daily_invokes != null ? Number(i.avg_daily_invokes).toFixed(2) : '—' },
          { label: 'TA Last Updated', value: formatDate(i.ta_last_updated) },
        ]} />
      </SpaceBetween>
      <SpaceBetween size="s">
        <Header variant="h3" description="We use GetFunctionConfiguration and ListTags API Actions to fetch the below data">Source: AWS Lambda</Header>
        <KeyValuePairs columns={1} items={[
          { label: 'Handler', value: i.handler || '—' },
          { label: 'Package Type', value: i.package_type || '—' },
          { label: 'Architecture', value: (i.architectures || ['x86_64']).join(', ') },
          { label: 'Memory', value: i.memory_size ? `${i.memory_size} MB` : '—' },
          { label: 'Timeout', value: i.timeout ? `${i.timeout}s` : '—' },
          { label: 'Code Size', value: formatBytes(i.code_size) },
          { label: 'Layers', value: layers.length > 0 ? layers.join(', ') : 'None' },
          { label: 'Tags', value: Object.keys(tags).length > 0 ? Object.entries(tags).map(([k, v]) => `${k}=${v}`).join(', ') : 'None' },
          { label: 'Env Vars', value: Object.keys(envVars).length > 0 ? Object.keys(envVars).join(', ') : 'None' },
        ]} />
      </SpaceBetween>
      <SpaceBetween size="s">
        <Header variant="h3" description="We use DescribeLogStreams and GetMetricStatistics API Actions to fetch the below data">Source: Amazon CloudWatch</Header>
        <KeyValuePairs columns={1} items={[
          { label: 'Last Invoked', value: formatDate(i.last_invocation_date) },
          { label: 'Invocations (14d)', value: i.invocation_count_14d != null ? Number(i.invocation_count_14d).toLocaleString() : '—' },
        ]} />
      </SpaceBetween>
      <SpaceBetween size="s">
        <Header variant="h3" description="AI-powered migration priority scoring based on deprecation urgency, invocation patterns, environment tags, and runtime age — Amazon Nova 2 Lite via Converse API">Source: Amazon Bedrock</Header>
        <GenAiLabel />
        <KeyValuePairs columns={1} items={[
          { label: 'Priority', value: (() => { const l = i.priority_label || '—'; return <Badge color={PRIORITY_COLORS[l] as any || 'grey'}>{l}</Badge>; })() },
          { label: 'Score', value: i.priority_score != null ? `${i.priority_score} / 100` : '—' },
          { label: 'Reasoning', value: i.priority_reasoning || '—' },
          { label: 'Status', value: (() => { const c = getStatusConfig(i.migration_status || 'DISCOVERED'); return <StatusIndicator type={c.type}>{c.label}</StatusIndicator>; })() },
        ]} />
      </SpaceBetween>
    </ColumnLayout>
    </Container>
    </SpaceBetween>
  );

  // ─── Assessment Tab ───
  const assessmentTab = (
    <SpaceBetween size="l">
      <Box variant="p" color="text-body-secondary">Downloads the function's deployment package, uploads source code to S3, then sends the actual code to Nova 2 Lite to identify deprecated APIs, breaking changes, dependency issues, and recommend a target runtime.</Box>
      {actionLoading === 'analyze' ? (
        <Box textAlign="center" padding="xxl"><Spinner size="large" /><Box variant="p" padding={{ top: 's' }}>Assessing function code...</Box></Box>
      ) : analyzeResult ? (
        <>
          <Container header={<Header variant="h3" description="We use the GetFunction API to download the deployment package, extract source files, count lines of code, and upload to S3 for analysis">Source: AWS Lambda</Header>}>
            <ColumnLayout columns={3} variant="text-grid">
              <KeyValuePairs columns={1} items={[
                { label: 'Lines of Code', value: String(analyzeResult.lines_of_code ?? '—') },
                { label: 'Source Files', value: String(analyzeResult.num_source_files ?? '—') },
              ]} />
              <KeyValuePairs columns={1} items={[
                { label: 'Current Runtime', value: String(analyzeResult.current_runtime || '—') },
                { label: 'Assessed At', value: formatDate(analyzeResult.assessed_at as string) },
              ]} />
              <KeyValuePairs columns={1} items={[
                { label: 'Code Path', value: <Box variant="code" fontSize="body-s">{String(analyzeResult.s3_original_code_path || '—')}</Box> },
                { label: 'Findings', value: <Box variant="code" fontSize="body-s">{String(analyzeResult.s3_findings_path || '—')}</Box> },
              ]} />
            </ColumnLayout>
          </Container>
          <Container header={
            <Header variant="h3" description="AI-powered code analysis identifying deprecated APIs, breaking changes, and migration complexity — Amazon Nova 2 Lite via Converse API">
              Source: Amazon Bedrock
            </Header>
          }>
            <SpaceBetween size="m">
              <GenAiLabel />
              <ColumnLayout columns={3} variant="text-grid">
                <KeyValuePairs columns={1} items={[
                  { label: 'Target Runtime', value: String(analyzeResult.target_runtime || '—') },
                  { label: 'Migration Path', value: `${analyzeResult.current_runtime || '?'} → ${analyzeResult.target_runtime || '?'}` },
                ]} />
                <KeyValuePairs columns={1} items={[
                  { label: 'Complexity', value: (() => { const c = String(analyzeResult.complexity || '—'); return <Badge color={PRIORITY_COLORS[c] as any || 'grey'}>{c}</Badge>; })() },
                ]} />
                <KeyValuePairs columns={1} items={[]} />
              </ColumnLayout>
              <Box variant="p">{String(analyzeResult.summary || '')}</Box>
              {(() => {
                const apis = analyzeResult.deprecated_apis as string[] || [];
                return apis.length > 0 ? (
                  <ExpandableSection headerText={`Deprecated APIs (${apis.length})`} defaultExpanded>
                    <ul>{apis.map((a, i) => <li key={i}>{a}</li>)}</ul>
                  </ExpandableSection>
                ) : null;
              })()}
              {(() => {
                const changes = analyzeResult.breaking_changes as string[] || [];
                return changes.length > 0 ? (
                  <ExpandableSection headerText={`Breaking Changes (${changes.length})`} defaultExpanded>
                    <ul>{changes.map((c, i) => <li key={i}>{c}</li>)}</ul>
                  </ExpandableSection>
                ) : null;
              })()}
              {(() => {
                const deps = analyzeResult.dependency_issues as string[] || [];
                return deps.length > 0 ? (
                  <ExpandableSection headerText={`Dependency Issues (${deps.length})`} defaultExpanded={false}>
                    <ul>{deps.map((d, i) => <li key={i}>{d}</li>)}</ul>
                  </ExpandableSection>
                ) : null;
              })()}
              {(() => {
                let risks = analyzeResult.migration_risks;
                if (!risks) return null;
                // Handle both string and array formats
                let riskList: string[] = [];
                if (typeof risks === 'string') {
                  try { riskList = JSON.parse(risks as string); } catch { riskList = [risks as string]; }
                } else if (Array.isArray(risks)) {
                  riskList = risks as string[];
                }
                return riskList.length > 0 ? (
                  <ExpandableSection headerText={`Migration Risks (${riskList.length})`} defaultExpanded={false}>
                    <ul>{riskList.map((r, i) => <li key={i}>{r}</li>)}</ul>
                  </ExpandableSection>
                ) : null;
              })()}
            </SpaceBetween>
          </Container>
        </>
      ) : (
        <Box textAlign="center" color="text-status-inactive" padding="xxl">
          Click "Assess" to run code assessment on this function.
        </Box>
      )}
    </SpaceBetween>
  );

  // ─── Transform Tab ───
  const transformTab = (
    <SpaceBetween size="l">
      <Box variant="p" color="text-body-secondary">Generates migrated code file-by-file using Nova 2 Lite, validates each Python file through Code Interpreter (ast.parse + import check), and retries up to 3 times on validation failure before storing the migration package in S3.</Box>
      {actionLoading === 'transform' ? (
        (() => {
          const done = transformProgress?.done ?? 0;
          const total = transformProgress?.total ?? 0;
          const phase = transformProgress?.phase;
          const attempt = transformProgress?.attempt ?? 1;
          const pct = total > 0 ? Math.round((done / total) * 100) : 0;
          const phaseLabel =
            phase === 'validating'
              ? `Validating migrated code in the Code Interpreter sandbox${attempt > 1 ? ` (attempt ${attempt}/3)` : ''}…`
              : phase === 'generating'
                ? `Generating migrated code — file ${done}/${total}${attempt > 1 ? ` (re-generating, attempt ${attempt}/3)` : ''}`
                : 'Starting transform…';
          return (
            <Container header={<Header variant="h3">Transformation in progress</Header>}>
              <SpaceBetween size="m">
                <Box><Spinner /> {phaseLabel}</Box>
                {total > 0 && (
                  <ProgressBar
                    value={phase === 'validating' ? 100 : pct}
                    label="Code generation"
                    description={
                      phase === 'validating'
                        ? 'All files generated — running syntax and import validation'
                        : `${done} of ${total} source files migrated`
                    }
                    additionalInfo={attempt > 1 ? `Retry attempt ${attempt} of 3` : undefined}
                  />
                )}
                <KeyValuePairs columns={2} items={[
                  { label: 'Elapsed', value: formatElapsed(elapsed) },
                  { label: 'Files', value: total > 0 ? `${done} / ${total}` : 'Determining…' },
                ]} />
                <Alert type="info">
                  Large functions can take several minutes. The migration runs in the background and results are
                  saved to S3 and DynamoDB even if this view times out — reopen this function later to see the outcome.
                </Alert>
              </SpaceBetween>
            </Container>
          );
        })()
      ) : transformResult ? (
        transformResult.error ? (
          <Alert type="error" header="Transform Failed">{String(transformResult.error)}</Alert>
        ) : (
          <>
            <Container header={<Header variant="h3" description="We store the migrated source files, changelog, and validation report in S3 for review and deployment">Source: Amazon S3</Header>}>
              <ColumnLayout columns={3} variant="text-grid">
                <KeyValuePairs columns={1} items={[
                  { label: 'Status', value: (() => {
                    const s = String(transformResult.migration_status || transformResult.status || '—');
                    if (s === 'READY_TO_MIGRATE') return <Badge color="severity-neutral">Ready to Migrate</Badge>;
                    if (s === 'TRANSFORM_FAILED') return <Badge color="severity-high">Failed</Badge>;
                    return <Badge color="grey">{s}</Badge>;
                  })() },
                  { label: 'Transformed At', value: formatDate(transformResult.transformed_at as string) },
                ]} />
                <KeyValuePairs columns={1} items={[
                  { label: 'S3 Path', value: <Box variant="code" fontSize="body-s">{String(transformResult.s3_path || '—')}</Box> },
                ]} />
                <KeyValuePairs columns={1} items={[
                  { label: 'Migrated Files', value: (transformResult.migrated_files as string[])?.join(', ') || '—' },
                ]} />
              </ColumnLayout>
            </Container>
            <Container header={
                <Header variant="h3" description="We generate migrated code file-by-file, sending each source file individually to produce runtime-compatible output from Phase 2 findings — Amazon Nova 2 Lite via Converse API">
              Source: Amazon Bedrock
            </Header>
            }>
              <GenAiLabel />
              {transformResult.changelog ? (
                <ExpandableSection headerText="Migration Changelog" defaultExpanded>
                  <ReactMarkdown remarkPlugins={[remarkGfm]}>{String(transformResult.changelog)}</ReactMarkdown>
                </ExpandableSection>
              ) : (
                <Box color="text-body-secondary">No breaking changes detected — migration is a runtime version bump with minimal or no code modifications.</Box>
              )}
            </Container>
            <Container header={
              <Header variant="h3" description="We validate the generated Python code in a secure sandbox by parsing the AST for syntax errors and checking that all standard library imports are present — Amazon Bedrock AgentCore Code Interpreter">
                Source: Amazon Bedrock AgentCore Code Interpreter
              </Header>
            }>
              <KeyValuePairs columns={3} items={[
                { label: 'Valid', value: (transformResult.validation as any)?.skipped
                  ? 'Skipped — no Python files'
                  : (transformResult.validation as any)?.valid ? 'Yes' : 'No' },
                { label: 'Errors', value: (transformResult.validation as any)?.errors?.length
                  ? ((transformResult.validation as any).errors as string[]).join('; ') : 'None' },
                { label: 'Attempts', value: (() => {
                  const v = transformResult.validation as any;
                  if (v?.skipped) return '—';
                  const passed = v?.passed_on_attempt || 0;
                  const max = v?.max_attempts || 3;
                  return passed > 0 ? `Passed on attempt ${passed}/${max}` : `Failed after ${max} attempts`;
                })() },
                { label: 'Files Validated', value: (() => {
                  const v = transformResult.validation as any;
                  return v?.skipped ? '—' : String(v?.files_validated ?? '—');
                })() },
                { label: 'Checks Performed', value: (() => {
                  const v = transformResult.validation as any;
                  return v?.skipped ? '—' : (v?.checks as string[])?.join(', ') || 'syntax (ast.parse)';
                })() },
              ]} />
            </Container>
          </>
        )
      ) : (
        <Box textAlign="center" color="text-status-inactive" padding="xxl">
          Click "Transform" to generate migrated code for this function.
        </Box>
      )}
    </SpaceBetween>
  );

  return (
    <SpaceBetween size="l">
      <Header variant="h1"
        actions={
          <SpaceBetween size="xs" direction="horizontal">
            <Button onClick={() => navigate('/functions')} iconName="arrow-left">Back</Button>
            <Button onClick={handleAnalyze} loading={actionLoading === 'analyze'} iconName="search">Assess</Button>
            <Button variant="primary" onClick={handleTransform} loading={actionLoading === 'transform'} iconName="caret-right-filled">Transform</Button>
          </SpaceBetween>
        }
      >
        {functionName.split(':')[0]}
      </Header>
      {actionError && <Alert type="error" dismissible onDismiss={() => setActionError(null)}>{actionError}</Alert>}
      <Tabs activeTabId={activeTab} onChange={({ detail }) => setActiveTab(detail.activeTabId)} tabs={[
        { label: 'Overview', id: 'overview', content: overviewTab },
        { label: 'Assessment', id: 'assessment', content: assessmentTab },
        { label: 'Transformation', id: 'transform', content: transformTab },
      ]} />
    </SpaceBetween>
  );
}
